title: Restaurant Home Page # 
logo: "https://falsel.github.io/images/logo.png"
description: >
  Software Developer
  <br><br>
  Enthusiastic Computer Engineering student (3.9/4.0) graduated August 2019 with experience building web and native applications. A learner who enjoys learning new techniques every day. Analytical and time management skills are my strength.
  Currently looking for a position as an IT Technologist/software developer to further my professional career. 
  <br><br>
  <a href="https://falsel.github.io/">Back to Portfolio</a>  
  
theme: jekyll-theme-minimal
